/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_paradigmasSV;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class FrmVentana extends javax.swing.JFrame {

    /**
     * Creates new form FrmVentana
     */
    ImagenFondo ejemplo = new ImagenFondo();
    
    public FrmVentana() {
        this.setContentPane(ejemplo);
        initComponents();
        super.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Seleccion = new javax.swing.JLabel();
        txtOpc = new javax.swing.JTextField();
        Encabezado = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        Opc1 = new javax.swing.JLabel();
        Opc3 = new javax.swing.JLabel();
        Opc4 = new javax.swing.JLabel();
        Opc5 = new javax.swing.JLabel();
        Opc6 = new javax.swing.JLabel();
        Opc7 = new javax.swing.JLabel();
        Opc8 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        jLabel7.setText("MENU");

        jLabel10.setText("6. SALIR");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        Seleccion.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 14)); // NOI18N
        Seleccion.setForeground(new java.awt.Color(255, 255, 0));
        Seleccion.setText("Escriba la opcion");
        Seleccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 153)));

        txtOpc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOpc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpcActionPerformed(evt);
            }
        });

        Encabezado.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 27)); // NOI18N
        Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Encabezado.setText("SISTEMA DE VENTAS Y PAGOS DIGITALES");

        btnSalir.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 0, 51));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        Opc1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        Opc1.setForeground(new java.awt.Color(255, 204, 204));
        Opc1.setText("1. RECARGA");

        Opc3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        Opc3.setForeground(new java.awt.Color(153, 255, 153));
        Opc3.setText("5. REPORTE VENTAS RECARGA");

        Opc4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        Opc4.setForeground(new java.awt.Color(51, 255, 204));
        Opc4.setText("4. REPORTE DE VENTAS PINES");

        Opc5.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        Opc5.setForeground(new java.awt.Color(255, 255, 0));
        Opc5.setText("7. CONSULTAR VENTA");

        Opc6.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        Opc6.setForeground(new java.awt.Color(255, 0, 255));
        Opc6.setText("2. PINES ELECTRONICOS");

        Opc7.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        Opc7.setForeground(new java.awt.Color(255, 204, 204));
        Opc7.setText("6. REPORTE VENTAS PAGO_SERV");

        Opc8.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        Opc8.setForeground(new java.awt.Color(255, 153, 51));
        Opc8.setText("3. PAGO DE SERVICIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Opc1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(Opc6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(Opc8)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Opc7, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Opc5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Opc4)
                        .addGap(55, 55, 55)
                        .addComponent(Opc3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Encabezado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(Seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOpc, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opc1)
                    .addComponent(Opc6)
                    .addComponent(Opc8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opc4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Opc3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opc5)
                    .addComponent(Opc7))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOpc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpcActionPerformed
        String opc;
        opc = txtOpc.getText();
        switch (opc) {
            case "1":
                DlgRecarga r = new DlgRecarga(this, true);
                r.setVisible(true);
            break;
            case "2":
                DlgPS ps = new DlgPS(this, true);
                ps.setVisible(true);
            break;
            case "3":
            DlgPN pn = new DlgPN(this, true);
            pn.setVisible(true);
            break;
            case "4":
                DlgReportePIN d = new DlgReportePIN(this, true);
                d.setVisible(true);
            break;
            case "5":
                 DlgReporteR de = new DlgReporteR(this, true);
                 de.setVisible(true);
            break;
            case "6":
               DlgReportePS sp = new DlgReportePS(this, true);
                sp.setVisible(true);
            break;
            case "7":
                DlgConsultar cc = new DlgConsultar(this, true);
                cc.setVisible(true);
            break;  
            default:
            JOptionPane.showMessageDialog(this, "Opción no válida");
        }
    }//GEN-LAST:event_txtOpcActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encabezado;
    private javax.swing.JLabel Opc1;
    private javax.swing.JLabel Opc3;
    private javax.swing.JLabel Opc4;
    private javax.swing.JLabel Opc5;
    private javax.swing.JLabel Opc6;
    private javax.swing.JLabel Opc7;
    private javax.swing.JLabel Opc8;
    private javax.swing.JLabel Seleccion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtOpc;
    // End of variables declaration//GEN-END:variables
    class ImagenFondo extends JPanel{
        //atributos
        private Image imagen;
        //Metodos
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("gre.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
        
    }
}
